<h1>Login de Acesso</h1>

<?php

$username = $form->get('username');
$username->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$password = $form->get('password');
$password->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('login'));
$form->prepare();

?>

<?php if ($messageError): ?>
    <div class="alert alert-danger fade in alert-dismissible show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="font-size:20px">×</span>
        </button>
        <strong>Erro!</strong> <?= $messageError; ?>
    </div>
<?php endif; ?>

<div class="row">
    <div class="col-md-3">
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($username); ?>
            <?= $this->formElement($username); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($password); ?>
            <?= $this->formElement($password); ?>
        </div>

        <?php
        //var_dump($message);
        echo $this->formSubmit($submit);
        //imprime o fechamento da tag form
        echo $this->form()->closeTag();
        ?>
    </div>
</div>