<h1>Add new Post</h1>

<?php

$title = $form->get('title');
$title->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$content = $form->get('content');
$content->setAttribute('class', 'form-control')
    ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$submit->setAttribute('value', 'Postar');

$form->setAttribute('action', $this->url('admin-blog/post', ['action' => 'add']));
$form->prepare();

//imprime o action do form
echo $this->form()->openTag($form);

?>

<?php $message = $this->formElementErrors($title, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : "" ?>">
    <?= $this->formLabel($title); ?>
    <?= $this->formElement($title); ?>
    <?= $message ?>
</div>

<?php $message = $this->formElementErrors($content, ['class' => 'help-block']); ?>
<div class="form-group<?= $message ? " has-error" : "" ?>">
    <?= $this->formLabel($content); ?>
    <?= $this->formElement($content); ?>
    <?= $message ?>
</div>

<?php
//var_dump($message);
echo $this->formSubmit($submit);

//input invisivel para guardar o id
echo $this->formHidden($form->get('id'));

//imprime o fechamento da tag form
echo $this->form()->closeTag();
?>
